# Generated by Django 3.0.2 on 2020-02-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddQuestions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='isimportant',
            new_name='isImportant',
        ),
    ]
