# Generated by Django 3.0.4 on 2020-03-12 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AddQuestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='courseID',
            field=models.TextField(default=datetime.datetime(2020, 3, 12, 16, 30, 18, 970792, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='isSelected',
            field=models.BooleanField(default=False),
        ),
    ]
