# Generated by Django 3.0.2 on 2020-02-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddQuestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='repeated',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
