# Generated by Django 3.0.4 on 2020-03-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('course1', models.CharField(default=None, max_length=6)),
                ('course2', models.CharField(default=None, max_length=6)),
                ('course3', models.CharField(default=None, max_length=6)),
                ('course4', models.CharField(default=None, max_length=6)),
                ('course5', models.CharField(default=None, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('course1', models.CharField(default=None, max_length=6)),
                ('course2', models.CharField(default=None, max_length=6)),
                ('course3', models.CharField(default=None, max_length=6)),
                ('course4', models.CharField(default=None, max_length=6)),
                ('course5', models.CharField(default=None, max_length=6)),
            ],
        ),
    ]
