# Generated by Django 3.0.4 on 2020-03-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200324_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourses',
            name='courseDescription',
        ),
        migrations.AddField(
            model_name='studentcourses',
            name='courseID',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
